name: Deploy React App to GitHub Pages

on:
  push:
    branches: ["main"]  # change if your default branch is different
  workflow_dispatch:   # allows manual trigger from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # change if your project requires a different version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the React app
      - name: Build React app
        run: npm run build

      # Step 5: Upload build folder as Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
